ALPACA_KEY =  'PK7S78UTYQN2I91TC4HL'
ALPACA_SECRET_KEY = 'VKg8w1EOGhaZdmollAKWhsEJ3Sqwv3eTZjZ0Qsdf'

HEADERS = {
    'APCA-API-KEY-ID':ALPACA_KEY,
    'APCA-API-SECRET-KEY': ALPACA_SECRET_KEY

}

ALPACA_API_BASE_URL = 'https://paper-api.alpaca.markets'